### ISSUE TITLE
provide json representation of run

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamClojureAPI#20]
To provide a format that is easier to consume and a cushion against changes in the server format, create functions within the client API that return JSON rather than the underlying XML.

When deciding on the schema for the JSON representation, the CIMI system and machine resources should be taken into account along with feedback from PAChA based on use of the run for calculating application prices.

**Comment by sixsq-hudson** [comment]
Why not doing it server-side as a facade in Clojure? And expose it in the api namespace?
