### ISSUE TITLE
document logging configuration for kvlt

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamClojureAPI#27]
Document the configuration for controlling the logging of kvlt.

**Comment by konstan** [comment]
`export TIMBRE_NS_BLACKLIST='["kvlt.*"]'`

kvlt is using https://github.com/ptaoussanis/timbre under the hood for logging - the simplest way would be to set the Timbre config, either at compile time (export TIMBRE_NS_BLACKLIST='["kvlt.*"]'), or runtime (see config examples in Timbre docs).
