### ISSUE TITLE
switch from clj-json to clojure.data.json

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamClojureAPI#34]
This affects the following files:
- `jar/project.clj`
- `jar/resources/deps.edn`
- `./jar/src/cljc/sixsq/slipstream/client/api/impl/cimi.cljc`
- `jar/src/cljc/sixsq/slipstream/client/api/impl/crud.cljc`

**Comment by konstan** [comment]
Just a minor comment.  There is no `jar/project.clj` anymore as the project is managed with boot.

**Comment by loomis** [comment]
Yes, I have a local `project.clj` file for IntelliJ integration, but it is indeed not a git managed file.
