### ISSUE TITLE
abstract out underlying http lib for easier interchange

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClojureAPI#4]
Use one of
- [Happy](https://github.com/jeluard/happy), cross-platform HTTP client
- [cljs-ajax](https://github.com/JulianBirch/cljs-ajax), cross-platform HTTP client

as proposed in 
https://github.com/SixSq/SlipStream/blob/master/roadmap.md#slipstream-client-code-convergence

**Comment by loomis** [comment]
There is also a new library, [kvlt](https://github.com/nervous-systems/kvlt) that allows interoperability between the browser, node, and clojure (JVM).  For the JVM it uses the [Aleph](https://github.com/ztellman/aleph) library, which is already a server-side dependency. [Docs and examples](https://github.com/nervous-systems/kvlt) are available. The library also supports web sockets and Server Sent Events (SSE).

**Comment by rbf** [comment]
@konstan: Have you had a look at [`http-kit`](https://github.com/http-kit/http-kit)? I don't know it further, but a first look shows that it's also server/client, supports Unified Async/Websocket API, and has [**zero dependencies**](https://github.com/http-kit/http-kit#hack-locally).
- http-kit/http-kit: http-kit is a minimalist, event-driven, high-performance Clojure HTTP server/client library with WebSocket and asynchronous support
  https://github.com/http-kit/http-kit
- HTTP client | http-kit, high performance HTTP Client/Server for Clojure
  http://www.http-kit.org/client.html

**Comment by loomis** [comment]
We used http-kit for the server until recently (now using Aleph).  I've not used the http-kit or Aleph clients in any detail. The code base of both seems to be of reasonable quality.
