### ISSUE TITLE
re-implement global library configuration via dynamic variable *config*

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClojureAPI#6]
Requirements come from @loomis [comment](https://github.com/slipstream/SlipStreamClientAPI/pull/2#issuecomment-185071808)

> Currently, the code reads the API's configuration from a file and puts the information into a global var that is read (directly or indirectly) from every function.  There are two problems with this:
> - Reading from a file will not be possible when using this API from ClojureScript in a browser.
> - This does not play well with concurrency where multiple threads may want to access different servers or different runs.
> 
> Although dynamic vars are a bit discouraged at the moment, global library configuration is one place where they still make sense.  I would recommend: 
> - Adding a dynamic variable to the `config` namespace that provides the map of configuration parameters for the full API. (This should not be in the run/run-impl namespaces as this is global to the full API.)
> - The configuration map should include the SlipStream server endpoint, user credentials, and HTTP connection parameters.
> - The configuration should not include things like the run id, which are specific to a particular resource. 
> - The root value for the configuration dynamic variable should only contain parameters that have a reasonable default, like whether the HTTP connections should be insecure (which should be false by default). 
> - Adding utility functions which allow the root binding or a thread-local binding to be merged with additional parameters.
> 
> Many people shun dynamic variable, so you should add an optional final parameter to all calls that takes an options/configuration map that will be merged with the value of the dynamic configuration var.
> 
> The documentation for the var should include all of the keys that are used in the configuration and what the appropriate values are.

**Comment by loomis** [comment]
You might also consider switching the configuration file format from ini to edn to avoid an external dependency.

**Comment by konstan** [comment]
The way the library is current designed and written is only to support scaling actions when running on Orchestrator.  And on the Orchestrator, the executor's contextualisation file (in `ini` format) is used as the configuration for the library.
